#! /bin/sh

set -e

#DEBHELPER#

case "$1" in
  configure)
	update-alternatives --install /etc/gdm/gdm-cdd.conf gdm-config-derivative /etc/xdg/neuroslink/gdm/gdm.conf 55

	if [ -e /etc/plse/default.pa ]; then
		cp /etc/pulse/default.pa /etc/pulse/default.pa.orig
		cp /etc/pulse/default.pa.neuroslink /etc/pulse/default.pa
	else
		echo "Pulse audio config not found so not installing"
	fi

# Currently nvidia hdmi required config is unknown
#	echo "ln -s /dev/snd/pcmC1D3p /dev/snd/pcmC1D0p" > /etc/rc.local
#	echo "amixer -c1 sset 'IEC958' unmute" >> /etc/rc.local
    ;;
esac
